spring:
  application:
    name: ai-Service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessDB
      database: fitnessDB


server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/